// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeUAzwfzfall_dDuNCFSDST-085frlrBk',
    appId: '1:369713265406:web:600dd0bdad13e70d5ac3af',
    messagingSenderId: '369713265406',
    projectId: 'expensewise-405d6',
    authDomain: 'expensewise-405d6.firebaseapp.com',
    storageBucket: 'expensewise-405d6.appspot.com',
    measurementId: 'G-3F0Y2XXHMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IEzT53G0bQReqPpPaXC6uub4An_fLFY',
    appId: '1:369713265406:android:551eadee63d22df55ac3af',
    messagingSenderId: '369713265406',
    projectId: 'expensewise-405d6',
    storageBucket: 'expensewise-405d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEhw_f_NOPRlRynollXl0WFFSGiFgDLl8',
    appId: '1:369713265406:ios:19005b06aa5ab4135ac3af',
    messagingSenderId: '369713265406',
    projectId: 'expensewise-405d6',
    storageBucket: 'expensewise-405d6.appspot.com',
    iosBundleId: 'com.example.expenseWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEhw_f_NOPRlRynollXl0WFFSGiFgDLl8',
    appId: '1:369713265406:ios:b0e1207e97ceebd05ac3af',
    messagingSenderId: '369713265406',
    projectId: 'expensewise-405d6',
    storageBucket: 'expensewise-405d6.appspot.com',
    iosBundleId: 'com.example.expenseWise.RunnerTests',
  );
}
